CREATE DATABASE fiber_db;
GRANT ALL PRIVILEGES ON fiber_db.* TO 'root'@'%';
USE fiber_db;

CREATE TABLE FACT (
  PERSON_KEY INTEGER DEFAULT NULL,
  ENCOUNTER_KEY INTEGER DEFAULT NULL,
  CAREGIVER_GROUP_KEY INTEGER DEFAULT NULL,
  FACILITY_KEY INTEGER DEFAULT NULL,
  PROCEDURE_GROUP_KEY INTEGER  DEFAULT NULL,
  DIAGNOSIS_GROUP_KEY INTEGER  DEFAULT NULL,
  MATERIAL_GROUP_KEY INTEGER  DEFAULT NULL,
  ORGANIZATION_GROUP_KEY SMALLINT DEFAULT NULL,
  TIME_OF_DAY_KEY SMALLINT DEFAULT NULL,
  META_DATA_KEY SMALLINT DEFAULT NULL,
  UOM_KEY SMALLINT DEFAULT NULL,
  DATA_STATE_KEY SMALLINT DEFAULT NULL,
  VALUE varchar(5000) DEFAULT NULL,
  AGE_IN_DAYS INTEGER  DEFAULT NULL
);

CREATE TABLE B_PROCEDURE (
  ID INTEGER,
  PROCEDURE_KEY INTEGER,
  PROCEDURE_GROUP_KEY INTEGER,
  PROCEDURE_ROLE varchar(100) DEFAULT NULL,
  PROCEDURE_RANK TINYINT DEFAULT NULL,
  PROCEDURE_WEIGHT_FACTOR TINYINT DEFAULT NULL
);

CREATE TABLE FD_PROCEDURE (
  ID INTEGER,
  PROCEDURE_KEY INTEGER,
  PROCEDURE_TYPE varchar(100) DEFAULT NULL,
  PROCEDURE_DESCRIPTION varchar(3000) DEFAULT '',
  SOURCE_NAME varchar(100) DEFAULT NULL,
  ACTIVE_FLAG varchar(20) DEFAULT NULL,
  ORPHAN_FLAG varchar(20) DEFAULT NULL,
  VALID_FLAG varchar(20) DEFAULT NULL,
  PROCEDURE_CONTROL_KEY INTEGER DEFAULT NULL,
  CONTEXT_PROCEDURE_CODE varchar(3000) DEFAULT NULL,
  CONTEXT_NAME varchar(50) DEFAULT NULL
);

CREATE TABLE B_MATERIAL (
  ID INTEGER DEFAULT NULL,
  MATERIAL_KEY INTEGER,
  MATERIAL_GROUP_KEY INTEGER,
  MATERIAL_ROLE varchar(100) DEFAULT NULL,
  MATERIAL_RANK TINYINT DEFAULT NULL,
  MATERIAL_WEIGHT_FACTOR TINYINT DEFAULT NULL
);

CREATE TABLE FD_MATERIAL (
  MATERIAL_KEY INTEGER,
  MATERIAL_TYPE varchar(100) DEFAULT NULL,
  MATERIAL_NAME varchar(4000) DEFAULT NULL,
  GENERIC_NAME varchar(500) DEFAULT NULL,
  BRAND1 varchar(250) DEFAULT NULL,
  BRAND2 varchar(250) DEFAULT NULL,
  SOURCE_NAME varchar(250) DEFAULT NULL,
  ACTIVE_FLAG varchar(20) DEFAULT NULL,
  ORPHAN_FLAG varchar(20) DEFAULT NULL,
  VALID_FLAG varchar(20) DEFAULT NULL,
  MATERIAL_CONTROL_KEY INTEGER DEFAULT NULL,
  CONTEXT_MATERIAL_CODE varchar(500) DEFAULT '',
  CONTEXT_NAME varchar(50) DEFAULT NULL
);

CREATE TABLE D_PERSON (
  PERSON_KEY INTEGER,
  PERSON_TYPE varchar(200) DEFAULT NULL,
  MEDICAL_RECORD_NUMBER varchar(20),
  MOTHER_ACCOUNT_NUMBER varchar(200) DEFAULT NULL,
  DATE_OF_BIRTH date DEFAULT NULL,
  GENDER varchar(20) DEFAULT NULL,
  RACE varchar(40) DEFAULT NULL,
  CITIZENSHIP varchar(40) DEFAULT NULL,
  LANGUAGE varchar(40) DEFAULT NULL,
  MARITAL_STATUS_CODE varchar(40) DEFAULT NULL,
  MARITAL_STATUS_LEGAL_IND varchar(40) DEFAULT NULL,
  MARITAL_STATUS_SOCIAL_IND varchar(40) DEFAULT NULL,
  MARITAL_STATUS_REASON varchar(40) DEFAULT NULL,
  RELIGION varchar(40) DEFAULT NULL,
  ADDRESS_TYPE varchar(40) DEFAULT NULL,
  ADDRESS_ZIP varchar(10) DEFAULT NULL,
  ADDRESS_ID varchar(20) DEFAULT NULL,
  DECEASED_INDICATOR varchar(20) DEFAULT NULL,
  LIVING_WILL_INDICATOR varchar(20) DEFAULT NULL,
  ACTIVE_INDICATOR varchar(20) DEFAULT NULL,
  ACTIVE_FLAG varchar(20) DEFAULT NULL,
  ORPHAN_FLAG varchar(20) DEFAULT NULL,
  VALID_FLAG varchar(20) DEFAULT NULL,
  SOURCE_NAME varchar(500) DEFAULT NULL,
  PERSON_CONTROL_KEY INTEGER DEFAULT NULL,
  PATIENT_ETHNIC_GROUP varchar(100) DEFAULT NULL,
  MONTH_OF_BIRTH varchar(100) DEFAULT NULL
);

CREATE TABLE D_ENCOUNTER (
  ENCOUNTER_KEY INTEGER,
  ENCOUNTER_TYPE varchar(100) DEFAULT NULL,
  ENCOUNTER_VISIT_ID varchar(200),
  ENCOUNTER_ACCOUNT_NUMBER varchar(200) DEFAULT NULL,
  MEDICAL_RECORD_NUMBER varchar(50),
  EVENT_TYPE varchar(20) DEFAULT NULL,
  ADMISSION_TYPE varchar(100) DEFAULT NULL,
  ENCOUNTER_CLASS varchar(100) DEFAULT NULL,
  ADMISSION_SOURCE varchar(200) DEFAULT NULL,
  ENCOUNTER_ACCOUNT_STATUS varchar(100) DEFAULT NULL,
  ENCOUNTER_SERVICE varchar(100) DEFAULT NULL,
  ENCOUNTER_ACCOMODATION varchar(200) DEFAULT NULL,
  SPECIALTY_UNIT varchar(50) DEFAULT NULL,
  DISCHARGE_DISPOSITION varchar(200) DEFAULT NULL,
  DISCHARGE_LOCATION_TO varchar(200) DEFAULT NULL,
  ESTIMATED_LENGTH_OF_STAY INTEGER DEFAULT -1,
  BEGIN_DATE_AGE_IN_DAYS INTEGER DEFAULT -1,
  END_DATE_AGE_IN_DAYS INTEGER DEFAULT -1,
  SOURCE_NAME varchar(100) DEFAULT NULL,
  ACTIVE_FLAG varchar(20) DEFAULT NULL,
  ORPHAN_FLAG varchar(20) DEFAULT NULL,
  VALID_FLAG varchar(20) DEFAULT NULL,
  ENCOUNTER_CONTROL_KEY INTEGER DEFAULT NULL,
  VISIT_OWNER varchar(200) DEFAULT NULL,
  ENCOUNTER_SUB_VISIT_ID varchar(200) DEFAULT NULL,
  EPIC_ENCOUNTER_TYPE varchar(200) DEFAULT NULL,
  MSDW_ENCOUNTER_TYPE varchar(200) DEFAULT NULL,
  EPIC_ENCOUNTER_STATUS varchar(200) DEFAULT NULL
);

CREATE TABLE D_UNIT_OF_MEASURE (
  UOM_KEY INTEGER,
  UOM_CLASS varchar(255) DEFAULT NULL,
  UNIT_OF_MEASURE varchar(255) DEFAULT NULL,
  SOURCE_NAME varchar(255) DEFAULT NULL,
  ACTIVE_FLAG varchar(20) DEFAULT NULL,
  ORPHAN_FLAG varchar(20) DEFAULT NULL
);

CREATE TABLE D_METADATA (
  META_DATA_KEY INTEGER,
  CONTEXT_KEY TINYINT,
  EXPECTED_UOM_KEY INTEGER,
  LEVEL1_CONTEXT_NAME varchar(255) DEFAULT NULL,
  LEVEL2_EVENT_NAME varchar(255) DEFAULT NULL,
  LEVEL3_ACTION_NAME varchar(255) DEFAULT NULL,
  LEVEL4_FIELD_NAME varchar(255) DEFAULT NULL,
  HIPAA_FLAG varchar(20) DEFAULT NULL,
  ACTIVE_FLAG varchar(20) DEFAULT NULL,
  ORPHAN_FLAG varchar(20) DEFAULT NULL
);

CREATE TABLE EPIC_LAB (
  ID INTEGER,
  ORDER_ID varchar(100) DEFAULT NULL,
  ORDER_LINE INTEGER DEFAULT NULL,
  MEDICAL_RECORD_NUMBER varchar(50),
  AGE_IN_DAYS INTEGER DEFAULT NULL,
  TEST_CODE INTEGER DEFAULT NULL,
  TEST_NAME varchar(1000) DEFAULT NULL,
  LAB_STATUS varchar(512) DEFAULT NULL,
  RESULT_STATUS varchar(512) DEFAULT NULL,
  RESULT_FLAG varchar(512) DEFAULT NULL,
  ABNORMAL_FLAG varchar(20) DEFAULT NULL,
  REFERENCE_RANGE varchar(512) DEFAULT NULL,
  UNIT_OF_MEASUREMENT varchar(512) DEFAULT NULL,
  TEST_RESULT_VALUE varchar(1000) DEFAULT NULL
);